In [26]:
import pandas as pd
import os
import gcamreader

# Source

* Data Source:
    * December 2020 Motor Vehicle Registration Statistics, Ministry of Land, Infrastructure and Transport (MOLIT). (`../resources/VRS-2020-MOLIT`)

* Implemented Input Files
    * `/input/policy/korea-2035/transportation/ZEV_calibrate.xml`

We calibrate ZEV service output using Korea’s 2020 ZEV enrollment data. The number of registered vehicles is converted into performance units based on the assumptions specified in `basic_assumption.ipynb`. For passenger cars, calibration in the model is further disaggregated into the `Car` and `Large Car and Truck` categories. Detailed implementation steps are provided below.

In [12]:
df = pd.read_excel("../resources/VRS-2020-MOLIT.xlsx", sheet_name="10.연료별_등록현황", skiprows=[0, 1])
df

,연료별,시도별,Unnamed: 2,서울,부산,대구,인천,광주,대전,울산,...,경기,강원,충북,충남,전북,전남,경북,경남,제주,계
0,NaN,종별,용도별,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,휘발유,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,승용,비사업용,1611157.0,659191.0,578131.0,652762.0,302504.0,332114.0,286856.0,...,2895301.0,344805.0,380173.0,497637.0,383217.0,366207.0,628286.0,813623.0,163448.0,10982274.0
4,NaN,NaN,사업용,20149.0,25034.0,3160.0,145108.0,1352.0,1662.0,948.0,...,12163.0,1538.0,2461.0,2259.0,3586.0,52564.0,1287.0,30567.0,100882.0,404842.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,NaN,NaN,사업용,4931.0,8890.0,2033.0,5296.0,1826.0,1646.0,2171.0,...,11282.0,1723.0,2737.0,2978.0,2205.0,4874.0,5038.0,5478.0,645.0,63918.0
286,NaN,NaN,계,8930.0,10989.0,3641.0,7639.0,2990.0,2802.0,3001.0,...,21554.0,3652.0,4574.0,5455.0,4245.0,7616.0,8230.0,8722.0,1417.0,105937.0
287,NaN,소계,비사업용,2953615.0,1295675.0,1168056.0,1318740.0,659540.0,656976.0,554016.0,...,5771837.0,783899.0,829617.0,1110156.0,908511.0,950516.0,1426974.0,1671248.0,384368.0,22615643.0
288,NaN,NaN,사업용,203746.0,133365.0,51140.0,357702.0,32200.0,29453.0,21684.0,...,232289.0,25200.0,36003.0,39689.0,39636.0,149378.0,48415.0,116619.0,230974.0,1750336.0
289,NaN,NaN,계,3157361.0,1429040.0,1219196.0,1676442.0,691740.0,686429.0,575700.0,...,6004126.0,809099.0,865620.0,1149845.0,948147.0,1099894.0,1475389.0,1787867.0,615342.0,24365979.0

In [13]:
df['연료별'] = df['연료별'].ffill()
df['시도별'] = df['시도별'].ffill()

In [14]:
df[(df['연료별'] == '전기') & (~df['계'].isna()) & (df['Unnamed: 2'] == '계')][['연료별', '시도별', 'Unnamed: 2',  '계']]

   연료별 시도별 Unnamed: 2         계
73  전기  승용          계  117616.0
76  전기  승합          계    1837.0
79  전기  화물          계   15436.0
82  전기  특수          계      73.0
85  전기  소계          계  134962.0

* 2020년 말 기준 전기승용차 등록대수(대): 117616.0
* 승용차 pass-km/veh/year = 33 * 365 * 1.26

In [15]:
# 전기승용 2020년 service output (million pass-km)
117616.0 * 33 * 365 * 1.26 / 1e6

1785.0227472000001

* 2020년 말 기준 전기버스 등록대수(대): 1837
* 버스 pass-km/veh/year = 824767

In [16]:
# 전기버스 2020년 service output (million pass-km)
1837 * 824767 / 1e6

1515.096979

* 2020년 말 기준 전기화물차 등록대수(대): 15436
* 화물차 ton-km/veh/year = 47 * 365 * 4.2

In [17]:
# 전기화물차 2020년 service output (million ton-km)
15436 * 47 * 365 * 4.2 / 1e6

1112.179236

In [18]:
df[(df['연료별'] == '수소') & (~df['계'].isna()) & (df['Unnamed: 2'] == '계')][['연료별', '시도별', 'Unnamed: 2',  '계']]

    연료별 시도별 Unnamed: 2        계
243  수소  승용          계  10831.0
246  수소  승합          계     75.0
249  수소  화물          계      0.0
252  수소  특수          계      0.0
255  수소  소계          계  10906.0

* 2020년 말 기준 수소승용차 등록대수(대): 10831
* 승용차 pass-km/veh/year = 33 * 365 * 1.26

In [19]:
# 수소승용 2020년 service output (million pass-km)
10831 * 33 * 365 * 1.26 / 1e6

164.3788377

* 2020년 말 기준 수소버스 등록대수(대): 75
* 버스 pass-km/veh/year = 824767

In [20]:
# 수소버스 2020년 service output (million pass-km)
75 * 824767 / 1e6

61.857525

* 2020년 말 기준 수소화물차 등록대수(대): 0
* 화물차 ton-km/veh/year = 47 * 365 * 4.2

In [21]:
# 전기화물차 2020년 service output (million ton-km)
0 * 47 * 365 * 4.2 / 1e6

0.0

In [29]:
dbpath = "../../output/"
dbfile = "database_basexdb"
conn = gcamreader.LocalDBConn(dbpath, dbfile)
queries = gcamreader.parse_batch_query(os.path.join('..', '..', 'output', 'queries','Main_queries.xml'))

Database scenarios: Reference, Macro

In [30]:
scenarios = list(conn.listScenariosInDB()['name'])
scenarios

['Reference', 'Macro']

In [31]:
for i, q in enumerate(queries):
    print(i, q.title)

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [32]:
i = 159
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=['Reference'], regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

transport service output by tech

,Units,scenario,region,sector,subsector,technology,Year,value
0,million pass-km,Reference,South Korea,trn_aviation_intl,International Aviation,BEV,2035,4.188620e-03
1,million pass-km,Reference,South Korea,trn_aviation_intl,International Aviation,BEV,2040,3.478500e-02
2,million pass-km,Reference,South Korea,trn_aviation_intl,International Aviation,BEV,2045,2.693970e-01
3,million pass-km,Reference,South Korea,trn_aviation_intl,International Aviation,BEV,2050,1.900340e+00
4,million pass-km,Reference,South Korea,trn_aviation_intl,International Aviation,BEV,2055,3.531650e+00
...,...,...,...,...,...,...,...,...
901,million ton-km,Reference,South Korea,trn_shipping_intl,International Ship,Liquids,2080,1.643780e+06
902,million ton-km,Reference,South Korea,trn_shipping_intl,International Ship,Liquids,2085,1.693100e+06
903,million ton-km,Reference,South Korea,trn_shipping_intl,International Ship,Liquids,2090,1.742860e+06
904,million ton-km,Reference,South Korea,trn_shipping_intl,International Ship,Liquids,2095,1.789120e+06
905,million ton-km,Reference,South Korea,trn_shipping_intl,International Ship,Liquids,2100,1.810670e+06

In [33]:
df[(df['Year'] == 2025) & (df['sector'].isin(['trn_pass_road_LDV_4W'])) & (df['technology'] == 'BEV')]

,Units,scenario,region,sector,subsector,technology,Year,value
405,million pass-km,Reference,South Korea,trn_pass_road_LDV_4W,Car,BEV,2025,12033.30
496,million pass-km,Reference,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,BEV,2025,5741.57

In [34]:
car_share = 12033.30 / (12033.30+5741.57)
car_share

0.676983854171648

In [35]:
1785.02 * car_share, 1785.02 * (1-car_share)

(1208.429719373475, 576.590280626525)

In [36]:
df[(df['Year'] == 2025) & (df['sector'].isin(['trn_pass_road_LDV_4W'])) & (df['technology'] == 'FCEV')]

,Units,scenario,region,sector,subsector,technology,Year,value
421,million pass-km,Reference,South Korea,trn_pass_road_LDV_4W,Car,FCEV,2025,434.735
512,million pass-km,Reference,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,FCEV,2025,164.938

In [37]:
car_share = 434.735 / (434.735+164.938)
car_share

0.7249534329542935

In [38]:
164.38 * car_share, 164.38 * (1-car_share)

(119.16784530902676, 45.212154690973236)