In [28]:
from pathlib import Path
import gcamreader
import os
import pandas as pd
import numpy as np
from utils import convert_to_mt
import plotly.graph_objects as go

In [29]:
cp_scen_nm = "Current-Policy"
ep_scen_nm = "Enhanced-Ambition"

In [30]:
def to_Mt(row):
    val, unit = row['value'], row['Units']
    if unit == 'Tg':
        return val
    elif unit == 'Gg':
        return val * 1e-3
    elif unit == 'MTC':
        return val * (44.009 / 12.011)
    else:
        raise ValueError(f"Unknown unit: {unit}")

# AR5 100-yr GWP
GWP_AR5 = {
    'CO2':    1,
    'CH4':    28,
    'N2O':    265,
    'HFC125': 3500,
    'HFC134a':1430,
    'HFC143a':4470,
    'HFC23':  14800,
    'HFC32':  675,
    'HFC43':  1500,
    'HFC227ea':3220,
    'HFC236fa':9810,
    'SF6':    23500,
    'C2F6':   12200,
    'CF4':    6630,
}

In [31]:
proj_path = Path("/data/project/tae/gcam-core")
xml_path = proj_path / "input" / "gcamdata" / "xml"
db_path = proj_path / "output"

In [32]:
dbpath = "../output/"  # relative to current working directory
dbfile = "database_basexdb_korea_2035_20250712"
conn = gcamreader.LocalDBConn(dbpath, dbfile)
queries = gcamreader.parse_batch_query(os.path.join('..', 'output', 'queries','Main_queries.xml'))

Database scenarios: Current-Policy, Enhanced-Ambition

In [33]:
scenarios = list(conn.listScenariosInDB()['name'])
scenarios

['Current-Policy', 'Enhanced-Ambition']

In [34]:
scenarios = [cp_scen_nm, ep_scen_nm]

In [35]:
for i, q in enumerate(queries):
    print(i, q.title)

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [36]:
q = queries[84]
print(q.title)
dfCO2 = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
dfCO2['scenario'] = dfCO2['scenario'].str.split(',').str[0]
dfCO2['GHG'] = 'CO2'
dfCO2

building service output by tech

,Units,scenario,region,sector,subsector,technology,Year,value,GHG
0,EJ,Current-Policy,South Korea,comm cooling,electricity,EE_electricity,2020,0.000014,CO2
1,EJ,Current-Policy,South Korea,comm cooling,electricity,EE_electricity,2025,0.000148,CO2
2,EJ,Current-Policy,South Korea,comm cooling,electricity,EE_electricity,2030,0.000274,CO2
3,EJ,Current-Policy,South Korea,comm cooling,electricity,EE_electricity,2035,0.000405,CO2
4,EJ,Current-Policy,South Korea,comm cooling,electricity,electricity,1990,0.007107,CO2
...,...,...,...,...,...,...,...,...,...
2460,EJ,Enhanced-Ambition,South Korea,resid others modern_d9,refined liquids,refined liquids,2015,0.004098,CO2
2461,EJ,Enhanced-Ambition,South Korea,resid others modern_d9,refined liquids,refined liquids,2020,0.003326,CO2
2462,EJ,Enhanced-Ambition,South Korea,resid others modern_d9,refined liquids,refined liquids,2025,0.003398,CO2
2463,EJ,Enhanced-Ambition,South Korea,resid others modern_d9,refined liquids,refined liquids,2030,0.002199,CO2
2464,EJ,Enhanced-Ambition,South Korea,resid others modern_d9,refined liquids,refined liquids,2035,0.001459,CO2

In [37]:
dfCO2['technology'].unique()

array(['EE_electricity', 'electricity', 'EE_gas', 'gas', 'biomass',
       'hydrogen', 'EE_refined liquids', 'refined liquids', 'coal',
       'traditional biomass'], dtype=object)

In [38]:
dfCO2[(dfCO2['sector'] == 'comm others')]

,Units,scenario,region,sector,subsector,technology,Year,value,GHG
71,EJ,Current-Policy,South Korea,comm others,biomass,biomass,1990,0.000053,CO2
72,EJ,Current-Policy,South Korea,comm others,biomass,biomass,2005,0.000301,CO2
73,EJ,Current-Policy,South Korea,comm others,biomass,biomass,2010,0.000589,CO2
74,EJ,Current-Policy,South Korea,comm others,biomass,biomass,2015,0.001680,CO2
75,EJ,Current-Policy,South Korea,comm others,biomass,biomass,2020,0.001660,CO2
...,...,...,...,...,...,...,...,...,...
1354,EJ,Enhanced-Ambition,South Korea,comm others,refined liquids,refined liquids,2015,0.030854,CO2
1355,EJ,Enhanced-Ambition,South Korea,comm others,refined liquids,refined liquids,2020,0.027869,CO2
1356,EJ,Enhanced-Ambition,South Korea,comm others,refined liquids,refined liquids,2025,0.030082,CO2
1357,EJ,Enhanced-Ambition,South Korea,comm others,refined liquids,refined liquids,2030,0.018290,CO2
1358,EJ,Enhanced-Ambition,South Korea,comm others,refined liquids,refined liquids,2035,0.011677,CO2

In [39]:
q = queries[262]
print(q.title)
dfCO2 = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
dfCO2['scenario'] = dfCO2['scenario'].str.split(',').str[0]
dfCO2['GHG'] = 'CO2'
q = queries[270]
print(q.title)
dfNonCO2 = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
dfNonCO2['scenario'] = dfNonCO2['scenario'].str.split(',').str[0]
dfGHG = pd.concat([dfCO2, dfNonCO2], axis=0)
dfGHG['emiss(MT)'] = dfGHG.apply(convert_to_mt, axis=1)
dfGHG['gwpAr5'] = dfGHG['GHG'].apply(lambda gas: GWP_AR5[gas] if gas in GWP_AR5 else np.nan)
dfGHG['MTCO2eq'] = dfGHG['emiss(MT)'] * dfGHG['gwpAr5']
dfGHG

CO2 emissions by sector (no bio) (excluding resource production)
nonCO2 emissions by sector (excluding resource production)

,Units,scenario,region,sector,Year,value,GHG,emiss(MT),gwpAr5,MTCO2eq
0,MTC,Current-Policy,South Korea,H2 central production,2020,0.002832,CO2,0.010385,1.0,0.010385
1,MTC,Current-Policy,South Korea,H2 central production,2025,0.011653,CO2,0.042728,1.0,0.042728
2,MTC,Current-Policy,South Korea,H2 central production,2030,0.004342,CO2,0.015919,1.0,0.015919
3,MTC,Current-Policy,South Korea,H2 central production,2035,0.008077,CO2,0.029615,1.0,0.029615
4,MTC,Current-Policy,South Korea,H2 wholesale dispensing,2020,0.002853,CO2,0.010460,1.0,0.010460
...,...,...,...,...,...,...,...,...,...,...
15510,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,2015,0.000206,SO2_2,0.000206,NaN,NaN
15511,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,2020,0.000210,SO2_2,0.000210,NaN,NaN
15512,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,2025,0.000206,SO2_2,0.000206,NaN,NaN
15513,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,2030,0.000204,SO2_2,0.000204,NaN,NaN
15514,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,2035,0.000200,SO2_2,0.000200,NaN,NaN

In [40]:
dfGHG['sector'].unique()

array(['H2 central production', 'H2 wholesale dispensing',
       'agricultural energy use', 'ammonia', 'backup_electricity',
       'cement', 'chemical energy use', 'chemical feedstocks',
       'comm cooling', 'comm heating', 'comm others',
       'construction energy use', 'construction feedstocks',
       'delivered biomass', 'delivered gas', 'desalinated water',
       'elec_coal (IGCC CCS)', 'elec_coal (conv pul CCS)',
       'elec_gas (CC CCS)', 'electricity', 'gas pipeline',
       'gas processing', 'iron and steel', 'mining energy use',
       'other industrial energy use', 'other industrial feedstocks',
       'process heat cement', 'process heat food processing',
       'process heat paper', 'refined liquids enduse',
       'refined liquids industrial', 'refining', 'resid heating coal_d1',
       'resid heating coal_d10', 'resid heating coal_d2',
       'resid heating coal_d3', 'resid heating coal_d4',
       'resid heating coal_d5', 'resid heating coal_d6',
       'resid heating coal_d7', 'resid heating coal_d8',
       'resid heating coal_d9', 'resid heating modern_d1',
       'resid heating modern_d10', 'resid heating modern_d2',
       'resid heating modern_d3', 'resid heating modern_d4',
       'resid heating modern_d5', 'resid heating modern_d6',
       'resid heating modern_d7', 'resid heating modern_d8',
       'resid heating modern_d9', 'resid others coal_d1',
       'resid others coal_d10', 'resid others coal_d2',
       'resid others coal_d3', 'resid others coal_d4',
       'resid others coal_d5', 'resid others coal_d6',
       'resid others coal_d7', 'resid others coal_d8',
       'resid others coal_d9', 'resid others modern_d1',
       'resid others modern_d10', 'resid others modern_d2',
       'resid others modern_d3', 'resid others modern_d4',
       'resid others modern_d5', 'resid others modern_d6',
       'resid others modern_d7', 'resid others modern_d8',
       'resid others modern_d9', 'trn_aviation_intl', 'trn_freight',
       'trn_freight_road', 'trn_pass', 'trn_pass_road',
       'trn_pass_road_LDV', 'trn_pass_road_LDV_4W', 'trn_shipping_intl',
       'waste biomass for paper', 'wholesale gas', 'airCO2',
       'process heat dac', 'electricity_net_ownuse',
       'industrial processes', 'resid cooling modern_d1',
       'resid cooling modern_d10', 'resid cooling modern_d2',
       'resid cooling modern_d3', 'resid cooling modern_d4',
       'resid cooling modern_d5', 'resid cooling modern_d6',
       'resid cooling modern_d7', 'resid cooling modern_d8',
       'resid cooling modern_d9', 'urban processes', 'Beef', 'Corn',
       'Dairy', 'FiberCrop', 'FodderGrass', 'Fruits', 'H2 liquid truck',
       'H2 pipeline', 'Legumes', 'MiscCrop', 'NutsSeeds', 'OilCrop',
       'OtherGrain', 'Pork', 'Poultry', 'Rice', 'RootTuber', 'SheepGoat',
       'Soybean', 'UnmanagedLand', 'Vegetables', 'Wheat', 'biomass',
       'resid heating TradBio_d1', 'resid heating TradBio_d10',
       'resid heating TradBio_d2', 'resid heating TradBio_d3',
       'resid heating TradBio_d4', 'resid heating TradBio_d5',
       'resid heating TradBio_d6', 'resid heating TradBio_d7',
       'resid heating TradBio_d8', 'resid heating TradBio_d9',
       'resid others TradBio_d1', 'resid others TradBio_d10',
       'resid others TradBio_d2', 'resid others TradBio_d3',
       'resid others TradBio_d4', 'resid others TradBio_d5',
       'resid others TradBio_d6', 'resid others TradBio_d7',
       'resid others TradBio_d8', 'resid others TradBio_d9'], dtype=object)

In [41]:
dfHist = pd.read_excel("./extdata/gir2025.xlsx", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ].reset_index()
dfHist

분야·부문/연도,index,총배출량,순배출량,에너지,A. 연료연소,1. 에너지산업,a. 공공전기 및 열 생산,b. 석유정제,c. 고체연료 제조 및 기타 에너지 산업,2. 제조업 및 건설업,...,1. 퇴비화,2. 바이오가스시설에서의 혐기성 소화,C. 폐기물소각 및 노천소각,1. 폐기물소각,2. 노천소각,D. 하폐수처리,1. 하수처리,2. 폐수처리,3. 기타,E. 기타
0,1990,310578.34,271615.09,234475.75,223481.61,42026.93,37174.66,4193.73,658.54,72169.01,...,0.00,0.00,560.85,560.85,0.0,729.52,631.05,98.48,0.0,0.0
1,1991,341241.27,306225.60,257328.69,246864.64,49945.73,43773.82,4978.80,1193.10,85306.81,...,0.00,0.00,746.36,746.36,0.0,911.36,793.36,118.00,0.0,0.0
2,1992,368809.57,334622.72,273752.07,264236.12,59044.99,51282.99,6097.80,1664.21,88857.58,...,0.00,0.00,879.08,879.08,0.0,1070.06,919.56,150.50,0.0,0.0
3,1993,406802.15,374169.23,303458.93,294738.32,66967.19,58078.04,6787.82,2101.33,97533.10,...,0.00,0.00,1083.73,1083.73,0.0,889.59,715.65,173.94,0.0,0.0
4,1994,432769.28,397753.22,323158.10,315376.07,81318.26,71719.31,7046.10,2552.86,102910.98,...,4.26,0.00,1547.93,1547.93,0.0,1513.83,1277.13,236.71,0.0,0.0
5,1995,464497.63,431236.45,347962.44,340964.77,91952.43,79555.15,9291.77,3105.51,104629.69,...,0.51,0.00,2212.85,2212.85,0.0,1520.26,1238.24,282.02,0.0,0.0
6,1996,501079.14,464394.65,381519.41,374951.00,115575.06,96643.67,10525.32,8406.07,106236.46,...,1.57,0.00,1607.51,1607.51,0.0,1561.24,1406.53,154.71,0.0,0.0
7,1997,526063.93,484380.56,398735.84,392509.74,124958.96,104573.97,13160.26,7224.74,107331.55,...,4.68,0.00,2014.38,2014.38,0.0,1381.70,1231.28,150.42,0.0,0.0
8,1998,460219.69,410168.46,340200.65,334224.21,112389.64,92499.17,13398.10,6492.37,97052.38,...,4.50,0.00,1901.37,1901.37,0.0,1631.16,1504.14,127.02,0.0,0.0
9,1999,500569.62,442315.49,372901.35,367093.36,122425.73,101887.04,13874.42,6664.27,104531.80,...,16.13,0.00,3245.30,3245.30,0.0,1728.48,1573.45,155.02,0.0,0.0
10,2000,533453.47,473061.31,402242.55,396534.49,136316.47,120792.07,13703.57,1820.83,115401.46,...,31.61,0.00,4324.17,4324.17,0.0,1776.27,1621.25,155.02,0.0,0.0
11,2001,550812.48,490089.66,415071.60,409514.28,147140.06,131947.47,13829.95,1362.65,115573.72,...,31.18,0.00,5033.51,5033.51,0.0,1823.72,1640.70,183.02,0.0,0.0
12,2002,570977.77,512616.42,432455.54,427242.47,155879.48,141601.16,13813.64,464.68,119477.53,...,46.76,0.00,4454.65,4454.65,0.0,2103.00,1887.33,215.67,0.0,0.0
13,2003,584476.01,526402.43,442261.22,437121.63,159850.25,145691.46,13373.72,785.07,124428.98,...,46.90,0.00,4623.69,4623.69,0.0,1888.95,1669.54,219.41,0.0,0.0
14,2004,595764.59,536330.06,451612.65,446579.58,172483.41,157379.12,13357.84,1746.45,125216.81,...,48.68,0.00,4578.31,4578.31,0.0,1808.66,1635.76,172.90,0.0,0.0
15,2005,594422.10,536941.52,448168.88,443255.72,177405.40,162392.92,13886.70,1125.78,116105.35,...,70.62,0.00,4836.83,4836.83,0.0,1856.49,1613.33,243.16,0.0,0.0
16,2006,607008.20,548343.58,458739.46,453920.99,187146.81,172208.58,13993.06,945.16,118786.89,...,85.30,0.00,5134.86,5134.86,0.0,1809.01,1648.69,160.32,0.0,0.0
17,2007,613628.85,554265.50,477326.58,472558.46,199499.84,184497.95,14232.55,769.34,124474.38,...,90.66,0.00,4393.35,4393.35,0.0,1914.98,1609.09,305.88,0.0,0.0
18,2008,628765.96,568477.01,490655.07,485963.02,212443.14,196168.26,15603.12,671.76,129047.56,...,93.39,0.00,4105.96,4105.96,0.0,1759.44,1473.80,285.64,0.0,0.0
19,2009,632655.33,572586.64,499155.99,494603.55,230654.69,214881.77,15174.71,598.21,119890.53,...,99.71,0.00,4136.62,4136.62,0.0,1784.22,1499.87,284.35,0.0,0.0
20,2010,689789.16,632427.78,550333.53,545924.68,254619.19,239940.44,14000.68,678.07,142754.06,...,80.43,9.28,4007.02,4007.02,0.0,1854.04,1504.98,349.06,0.0,0.0
21,2011,721638.20,665101.19,580221.09,575832.26,264989.86,248766.75,15338.70,884.41,164099.13,...,95.65,10.56,4715.25,4715.25,0.0,2041.60,1429.84,611.76,0.0,0.0
22,2012,720241.15,669678.63,575024.48,570624.86,269449.64,253153.13,15179.08,1117.44,154587.54,...,100.63,11.36,5317.14,5317.14,0.0,1838.32,1440.85,397.47,0.0,0.0
23,2013,728409.12,682146.30,569701.72,565485.67,276150.91,260234.49,14770.47,1145.94,142093.93,...,122.80,10.50,5372.52,5372.52,0.0,1965.34,1435.27,530.07,0.0,0.0
24,2014,724307.64,677165.03,560877.46,556806.27,263946.83,244674.75,18515.18,756.91,151263.95,...,137.84,16.96,4934.44,4934.44,0.0,1844.18,1382.40,461.78,0.0,0.0
25,2015,726104.80,678331.90,562925.48,558943.33,262303.04,244475.12,17159.36,668.55,148384.08,...,151.30,72.00,5233.33,5233.33,0.0,1653.35,1280.07,373.28,0.0,0.0
26,2016,737407.96,689192.24,575019.94,571076.03,263821.49,244752.99,18404.71,663.79,152592.81,...,164.00,88.91,5255.08,5255.08,0.0,1821.45,1320.57,500.87,0.0,0.0
27,2017,759107.77,716258.96,587475.36,583709.51,275085.79,256626.37,17274.70,1184.71,153094.48,...,167.17,86.18,5475.61,5475.61,0.0,1877.90,1236.78,641.13,0.0,0.0
28,2018,783873.57,742309.94,612119.82,608431.82,299963.55,278849.10,20289.60,824.84,153544.63,...,197.69,81.74,5072.10,5072.10,0.0,1675.90,1246.61,429.28,0.0,0.0
29,2019,759396.76,720742.44,586435.20,582881.59,279423.24,257946.60,20581.16,895.47,148841.57,...,210.40,81.17,4948.30,4948.30,0.0,1432.15,1251.40,180.76,0.0,0.0
30,2020,712958.78,674120.27,544600.21,541142.13,248224.38,228394.84,19158.74,670.81,144905.59,...,187.23,96.37,4684.65,4684.65,0.0,1500.57,1270.40,230.17,0.0,0.0
31,2021,740976.09,701974.88,566782.43,563361.94,260019.97,240292.40,18753.24,974.33,152932.44,...,196.16,100.12,4693.05,4693.05,0.0,1583.43,1290.82,292.60,0.0,0.0
32,2022,724294.06,686461.91,551889.33,548487.42,257501.95,237677.49,18425.52,1398.94,140999.10,...,205.58,79.50,4483.62,4483.62,0.0,1823.36,1275.16,548.19,0.0,0.0

In [42]:
dfHistCO2 = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="CO2", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistCO2

분야·부문/연도,총배출량,순배출량,에너지,A. 연료연소,1. 에너지산업,a. 공공전기 및 열 생산,b. 석유정제,c. 고체연료 제조 및 기타 에너지 산업,2. 제조업 및 건설업,a. 철강,...,1. 퇴비화,2. 바이오가스시설에서의 혐기성 소화,C. 폐기물소각 및 노천소각,1. 폐기물소각,2. 노천소각,D. 하폐수처리,1. 하수처리,2. 폐수처리,3. 기타,E. 기타
1990,256216.01,216831.36,219131.09,218944.11,41885.67,37044.76,4183.18,657.73,71922.38,27806.85,...,0.0,0.0,530.01,530.01,0.0,0.0,0.0,0.0,0.0,0.0
1991,286190.99,250790.40,242917.02,242753.45,49781.26,43623.51,4965.94,1191.81,85016.98,35147.82,...,0.0,0.0,705.28,705.28,0.0,0.0,0.0,0.0,0.0,0.0
1992,310353.52,275791.86,260584.43,260454.36,58854.01,51109.72,6081.84,1662.45,88560.19,37175.68,...,0.0,0.0,828.76,828.76,0.0,0.0,0.0,0.0,0.0,0.0
1993,347747.49,314771.79,291228.60,291125.90,66746.03,57876.59,6770.02,2099.41,97206.23,41547.99,...,0.0,0.0,1022.29,1022.29,0.0,0.0,0.0,0.0,0.0,0.0
1994,372197.71,336861.99,312113.66,312032.68,81046.89,71469.05,7027.56,2550.27,102557.48,41310.10,...,0.0,0.0,1476.73,1476.73,0.0,0.0,0.0,0.0,0.0,0.0
1995,401672.09,368091.79,337646.34,337583.94,91650.47,79276.27,9271.65,3102.56,104272.86,42942.78,...,0.0,0.0,2113.79,2113.79,0.0,0.0,0.0,0.0,0.0,0.0
1996,437066.43,400046.07,371494.17,371440.03,115179.69,96299.15,10501.91,8378.64,105882.54,43477.75,...,0.0,0.0,1508.67,1508.67,0.0,0.0,0.0,0.0,0.0,0.0
1997,457947.28,415925.84,388838.92,388789.45,124533.55,104197.73,13134.09,7201.73,106961.91,41549.44,...,0.0,0.0,1904.74,1904.74,0.0,0.0,0.0,0.0,0.0,0.0
1998,395004.07,344595.47,331253.17,331205.32,111984.27,92143.63,13371.07,6469.57,96730.74,42478.94,...,0.0,0.0,1797.16,1797.16,0.0,0.0,0.0,0.0,0.0,0.0
1999,430541.96,371940.93,363860.10,363813.91,121984.10,101496.92,13845.90,6641.28,104200.76,44929.72,...,0.0,0.0,3118.80,3118.80,0.0,0.0,0.0,0.0,0.0,0.0
2000,462622.90,401764.15,393013.92,392968.12,135819.70,120324.83,13676.08,1818.79,114987.63,46609.47,...,0.0,0.0,4160.39,4160.39,0.0,0.0,0.0,0.0,0.0,0.0
2001,482256.23,421161.45,405779.55,405737.31,146598.02,131435.29,13801.88,1360.84,115154.42,46822.91,...,0.0,0.0,4858.63,4858.63,0.0,0.0,0.0,0.0,0.0,0.0
2002,500515.37,441740.76,423345.65,423308.76,155303.27,141053.97,13785.72,463.58,119063.51,49156.15,...,0.0,0.0,4284.72,4284.72,0.0,0.0,0.0,0.0,0.0,0.0
2003,512504.25,454045.34,433207.21,433170.49,159257.12,145126.17,13347.33,783.62,123985.46,50181.79,...,0.0,0.0,4444.34,4444.34,0.0,0.0,0.0,0.0,0.0,0.0
2004,521860.65,462049.06,442682.46,442637.89,171855.01,156779.28,13331.83,1743.90,124769.09,52771.30,...,0.0,0.0,4398.89,4398.89,0.0,0.0,0.0,0.0,0.0,0.0
2005,521261.42,463416.59,439273.03,439216.70,176753.14,161773.07,13858.90,1121.18,115686.29,46994.38,...,0.0,0.0,4683.18,4683.18,0.0,0.0,0.0,0.0,0.0,0.0
2006,533407.91,474365.28,449840.13,449786.77,186465.45,171559.19,13965.52,940.73,118351.23,49513.19,...,0.0,0.0,4985.73,4985.73,0.0,0.0,0.0,0.0,0.0,0.0
2007,546650.86,486896.26,468376.11,468327.24,198786.72,183816.94,14204.72,765.06,124007.66,55225.54,...,0.0,0.0,4228.18,4228.18,0.0,0.0,0.0,0.0,0.0,0.0
2008,561050.64,500351.62,481693.45,481651.10,211668.54,195425.03,15575.43,668.08,128555.39,59446.31,...,0.0,0.0,3940.21,3940.21,0.0,0.0,0.0,0.0,0.0,0.0
2009,564255.15,503782.75,490230.31,490178.42,229789.41,214045.02,15149.36,595.03,119426.70,51604.28,...,0.0,0.0,3979.47,3979.47,0.0,0.0,0.0,0.0,0.0,0.0
2010,618047.38,560297.94,541305.62,541256.16,253692.74,239037.82,13979.79,675.14,142222.20,69169.00,...,0.0,0.0,3817.67,3817.67,0.0,0.0,0.0,0.0,0.0,0.0
2011,652029.53,595086.84,571125.78,571080.61,264016.86,247819.58,15317.36,879.91,163534.49,84382.40,...,0.0,0.0,4523.56,4523.56,0.0,0.0,0.0,0.0,0.0,0.0
2012,648655.62,597715.89,565908.27,565863.73,268491.43,252218.81,15160.25,1112.38,154066.97,82132.35,...,0.0,0.0,5092.93,5092.93,0.0,0.0,0.0,0.0,0.0,0.0
2013,654661.84,608019.58,560920.06,560877.26,275114.77,259272.77,14751.99,1090.01,141594.95,69645.11,...,0.0,0.0,5141.64,5141.64,0.0,0.0,0.0,0.0,0.0,0.0
2014,647520.10,599988.99,552240.70,552205.35,262954.54,243704.29,18494.49,755.76,150708.01,81343.94,...,0.0,0.0,4710.55,4710.55,0.0,0.0,0.0,0.0,0.0,0.0
2015,651088.83,602888.55,554205.32,554176.10,261272.55,243465.66,17139.28,667.62,147806.10,77781.73,...,0.0,0.0,4998.18,4998.18,0.0,0.0,0.0,0.0,0.0,0.0
2016,661823.14,613195.77,566243.04,566215.70,262841.02,243797.93,18380.13,662.96,151972.96,77397.40,...,0.0,0.0,5033.85,5033.85,0.0,0.0,0.0,0.0,0.0,0.0
2017,679647.01,636389.98,578285.02,578251.56,273747.56,255315.44,17249.14,1182.98,152413.15,77299.89,...,0.0,0.0,5254.04,5254.04,0.0,0.0,0.0,0.0,0.0,0.0
2018,701069.26,659105.11,602859.95,602831.12,298516.83,277427.74,20265.22,823.88,152832.28,79870.50,...,0.0,0.0,4848.64,4848.64,0.0,0.0,0.0,0.0,0.0,0.0
2019,675177.40,636086.53,577608.70,577583.41,278064.80,256617.00,20556.68,891.12,148151.18,78233.12,...,0.0,0.0,4745.75,4745.75,0.0,0.0,0.0,0.0,0.0,0.0
2020,626722.33,587440.20,536145.09,536124.04,247019.47,227215.11,19134.40,669.97,144234.81,75305.81,...,0.0,0.0,4456.72,4456.72,0.0,0.0,0.0,0.0,0.0,0.0
2021,652481.15,613063.49,558205.24,558191.37,258742.77,239039.86,18730.26,972.66,152213.81,78805.76,...,0.0,0.0,4472.80,4472.80,0.0,0.0,0.0,0.0,0.0,0.0
2022,635818.44,597381.20,543378.87,543368.24,256216.84,236415.87,18404.97,1396.00,140313.40,70228.67,...,0.0,0.0,4263.31,4263.31,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
dfHistCO2 = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="CO2", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistCH4 = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="CH4", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistN2O = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="N2O", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistSF6 = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="SF6", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistHFC = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="HFCs", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistPFC = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="PFCs", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
# dfHistNF3 = pd.read_excel("./extdata/gir2025.xlsx", sheet_name="NF3", skiprows=3, index_col=1, skipfooter=9).transpose().iloc[1:, ]
dfHistGas = pd.DataFrame({
    "CO2": dfHistCO2['총배출량'],
    "CH4": dfHistCH4['총배출량'],
    "N2O": dfHistN2O['총배출량'],
    "F-Gases": dfHistSF6['총배출량'] + dfHistHFC['총배출량'] + dfHistPFC['총배출량'],# + dfHistNF3['총배출량'],
})
dfHistGas.reset_index(inplace=True, names=['Year'])
# Compute cumulative stack
dfHistGas['CO2_stack'] = dfHistGas['CO2'] / 1000
dfHistGas['CH4_stack'] = (dfHistGas['CO2'] + dfHistGas['CH4']) / 1000
dfHistGas['N2O_stack'] = (dfHistGas['CO2'] + dfHistGas['CH4'] + dfHistGas['N2O']) / 1000
dfHistGas['FGas_stack'] = (dfHistGas['CO2'] + dfHistGas['CH4'] + dfHistGas['N2O'] + dfHistGas['F-Gases']) / 1000
dfHistGas

,Year,CO2,CH4,N2O,F-Gases,CO2_stack,CH4_stack,N2O_stack,FGas_stack
0,1990,256216.01,46817.79,6333.87,1210.67,256.21601,303.03380,309.36767,310.57834
1,1991,286190.99,47134.11,6744.65,1171.51,286.19099,333.32510,340.06975,341.24126
2,1992,310353.52,47269.47,8863.54,2323.05,310.35352,357.62299,366.48653,368.80958
3,1993,347747.49,47130.25,9309.21,2615.20,347.74749,394.87774,404.18695,406.80215
4,1994,372197.71,47350.74,10044.89,3175.94,372.19771,419.54845,429.59334,432.76928
5,1995,401672.09,47099.73,10901.91,4823.90,401.67209,448.77182,459.67373,464.49763
6,1996,437066.43,47050.01,11866.50,5096.20,437.06643,484.11644,495.98294,501.07914
7,1997,457947.28,47028.11,12784.21,8304.33,457.94728,504.97539,517.75960,526.06393
8,1998,395004.07,45635.72,13009.24,6570.65,395.00407,440.63979,453.64903,460.21968
9,1999,430541.96,44850.68,13910.74,11266.25,430.54196,475.39264,489.30338,500.56963
10,2000,462622.90,44629.47,14854.31,11346.79,462.62290,507.25237,522.10668,533.45347
11,2001,482256.23,44909.87,15125.61,8520.76,482.25623,527.16610,542.29171,550.81247
12,2002,500515.37,44518.41,15148.70,10795.29,500.51537,545.03378,560.18248,570.97777
13,2003,512504.25,44251.43,17855.85,9864.47,512.50425,556.75568,574.61153,584.47600
14,2004,521860.65,42439.64,20002.88,11461.42,521.86065,564.30029,584.30317,595.76459
15,2005,521261.42,42147.77,18796.96,12215.95,521.26142,563.40919,582.20615,594.42210
16,2006,533407.91,41863.79,18074.75,13661.74,533.40791,575.27170,593.34645,607.00819
17,2007,546650.86,41119.75,10654.19,15204.05,546.65086,587.77061,598.42480,613.62885
18,2008,561050.64,40766.96,9975.39,16613.06,561.05064,601.81760,611.79299,628.40605
19,2009,564255.15,40751.12,10284.28,17023.82,564.25515,605.00627,615.29055,632.31437
20,2010,618047.38,40620.56,10597.58,20137.40,618.04738,658.66794,669.26552,689.40292
21,2011,652029.53,39480.90,9730.19,19883.47,652.02953,691.51043,701.24062,721.12409
22,2012,648655.62,38887.54,10200.16,21695.19,648.65562,687.54316,697.74332,719.43851
23,2013,654661.84,38137.31,10206.56,24577.29,654.66184,692.79915,703.00571,727.58300
24,2014,647520.10,37973.34,10237.03,27746.88,647.52010,685.49344,695.73047,723.47735
25,2015,651088.83,37783.77,10092.51,26292.05,651.08883,688.87260,698.96511,725.25716
26,2016,661823.14,37582.15,10318.53,26931.12,661.82314,699.40529,709.72382,736.65494
27,2017,679647.01,37874.19,10589.91,30153.19,679.64701,717.52120,728.11111,758.26430
28,2018,701069.26,37164.10,10869.22,33803.32,701.06926,738.23336,749.10258,782.90590
29,2019,675177.40,35951.96,10992.73,36123.92,675.17740,711.12936,722.12209,758.24601
30,2020,626722.33,35569.06,10691.08,37849.10,626.72233,662.29139,672.98247,710.83157
31,2021,652481.15,35340.32,10799.34,40563.55,652.48115,687.82147,698.62081,739.18436
32,2022,635818.44,35150.76,10700.90,40969.58,635.81844,670.96920,681.67010,722.63968

In [44]:
dfOut = dfGHG[~(dfGHG['sector'].isin(['trn_aviation_intl', 'trn_shipping_intl']))].groupby(['scenario', 'Year'])['MTCO2eq'].sum().reset_index()
dfOut.rename(columns={'MTCO2eq': 'value'}, inplace=True)
dfOut['Units'] = 'MTCO2eq'

In [45]:
dfOut = dfOut.set_index(['scenario', 'Year'])
offset = 0 #624.5255 - 621.1791
dfOut.loc[(cp_scen_nm, 2005), 'value'] -= 57.5
dfOut.loc[(cp_scen_nm, 2010), 'value'] -= 57.3
dfOut.loc[(cp_scen_nm, 2015), 'value'] -= 47.8
dfOut.loc[(cp_scen_nm, 2020), 'value'] -= (38.8 + offset)
dfOut.loc[(cp_scen_nm, 2025), 'value'] -= (30.4 + offset)
dfOut.loc[(cp_scen_nm, 2030), 'value'] -= (21.8 + offset)
dfOut.loc[(cp_scen_nm, 2035), 'value'] -= (13.2 + offset)
dfOut.loc[(ep_scen_nm, 2005), 'value'] -= 57.5
dfOut.loc[(ep_scen_nm, 2010), 'value'] -= 57.3
dfOut.loc[(ep_scen_nm, 2015), 'value'] -= 47.8
dfOut.loc[(ep_scen_nm, 2020), 'value'] -= 38.8
dfOut.loc[(ep_scen_nm, 2025), 'value'] -= 30.4
dfOut.loc[(ep_scen_nm, 2030), 'value'] -= 38.8
dfOut.loc[(ep_scen_nm, 2035), 'value'] -= 47.8
dfOut = dfOut.reset_index()

In [46]:
dfOut

             scenario  Year       value    Units
0      Current-Policy  1975   41.320031  MTCO2eq
1      Current-Policy  1990  274.711343  MTCO2eq
2      Current-Policy  2005  495.845816  MTCO2eq
3      Current-Policy  2010  597.361819  MTCO2eq
4      Current-Policy  2015  656.830290  MTCO2eq
5      Current-Policy  2020  638.416459  MTCO2eq
6      Current-Policy  2025  624.032674  MTCO2eq
7      Current-Policy  2030  567.341834  MTCO2eq
8      Current-Policy  2035  493.645347  MTCO2eq
9   Enhanced-Ambition  1975   41.320031  MTCO2eq
10  Enhanced-Ambition  1990  274.711343  MTCO2eq
11  Enhanced-Ambition  2005  495.845816  MTCO2eq
12  Enhanced-Ambition  2010  597.361819  MTCO2eq
13  Enhanced-Ambition  2015  656.830290  MTCO2eq
14  Enhanced-Ambition  2020  638.416459  MTCO2eq
15  Enhanced-Ambition  2025  623.929648  MTCO2eq
16  Enhanced-Ambition  2030  466.057696  MTCO2eq
17  Enhanced-Ambition  2035  301.451733  MTCO2eq

In [20]:
dfPower = dfGHG[(dfGHG['sector'].str.contains('elec'))]# | (dfGHG['sector'].isin(lstOtherPower))].copy()
dfOutPower = dfPower.groupby(['scenario', 'region', 'Year'])['MTCO2eq'].sum().reset_index()
dfOutPower.rename(columns={'MTCO2eq': 'value'}, inplace=True)
dfOutPower['Units'] = 'MTCO2eq'
dfOutPower

             scenario       region  Year       value    Units
0      Current-Policy  South Korea  1990   35.315064  MTCO2eq
1      Current-Policy  South Korea  2005  177.820212  MTCO2eq
2      Current-Policy  South Korea  2010  251.589396  MTCO2eq
3      Current-Policy  South Korea  2015  260.227190  MTCO2eq
4      Current-Policy  South Korea  2020  246.910617  MTCO2eq
5      Current-Policy  South Korea  2025  211.221179  MTCO2eq
6      Current-Policy  South Korea  2030  165.716890  MTCO2eq
7      Current-Policy  South Korea  2035  122.260760  MTCO2eq
8   Enhanced-Ambition  South Korea  1990   35.315064  MTCO2eq
9   Enhanced-Ambition  South Korea  2005  177.820212  MTCO2eq
10  Enhanced-Ambition  South Korea  2010  251.589396  MTCO2eq
11  Enhanced-Ambition  South Korea  2015  260.227190  MTCO2eq
12  Enhanced-Ambition  South Korea  2020  246.910617  MTCO2eq
13  Enhanced-Ambition  South Korea  2025  211.220672  MTCO2eq
14  Enhanced-Ambition  South Korea  2030  142.113063  MTCO2eq
15  Enhanced-Ambition  South Korea  2035   59.930057  MTCO2eq

In [51]:
fig = go.Figure()

# emiss_2018 = 727.6
emiss_2018 = 783.8
# emiss_2018_net = 742.31
x_center = 2040
width = 1
# offset = 4.9574  # BPESD upward shift

emiss_2035_cur = dfOut.set_index(['scenario', 'Year'])['value'].get((cp_scen_nm, 2035))
emiss_2035_enh = dfOut.set_index(['scenario', 'Year'])['value'].get((ep_scen_nm, 2035))

reduc_cur = (1 - (emiss_2035_cur / emiss_2018)) * 100
reduc_enh = (1 - (emiss_2035_enh / emiss_2018)) * 100

# === Legend Group: Gases ===
# fig.add_trace(go.Scatter(
#     x=[None], y=[None], mode='lines',
#     line=dict(color='rgba(0,0,0,0)'),
#     name='<b>Sector</b>', showlegend=True, hoverinfo='skip'
# ))

# fig.add_trace(go.Scatter(
#     x=dfHist['index'],
#     y=dfHist['순배출량'] / 1000,
#     mode='lines', name='Total GHG (incl. LULUCF)',
#     line=dict(color='black', width=1)
# ))


# fig.add_trace(go.Scatter(
#     x=dfHist['index'],
#     y=dfHist['a. 공공전기 및 열 생산'] / 1000,
#     mode='lines', name='Electricity',
#     line=dict(color='black', width=1, dash='dash')
# ))

# === Legend Group: Gases ===
fig.add_trace(go.Scatter(
    x=[None], y=[None], mode='lines',
    line=dict(color='rgba(0,0,0,0)'),
    name='<br><br><br><b>Gas</b>', showlegend=True, hoverinfo='skip'
))
fig.add_trace(go.Scatter(x=dfHistGas['Year'], y=dfHistGas['CO2_stack'],
    mode='lines', name='CO2', fill='tozeroy',
    line=dict(width=0.5, color='grey')
))
fig.add_trace(go.Scatter(x=dfHistGas['Year'], y=dfHistGas['CH4_stack'],
    mode='lines', name='CH4', fill='tonexty',
    line=dict(width=0.5, color='green')
))
fig.add_trace(go.Scatter(x=dfHistGas['Year'], y=dfHistGas['N2O_stack'],
    mode='lines', name='N2O', fill='tonexty',
    line=dict(width=0.5, color='purple')
))
fig.add_trace(go.Scatter(x=dfHistGas['Year'], y=dfHistGas['FGas_stack'],
    mode='lines', name='F-Gases', fill='tonexty',
    line=dict(width=0.5, color='yellow')
))

fig.add_trace(go.Scatter(
    x=[2030], y=[emiss_2018 * 0.6 + 37.5],
    mode='markers+text',
    marker=dict(color='#750D86', size=7, symbol='triangle-up'),
    text='2030 NDC', textposition="middle left",
    textfont=dict(size=15, color="#750D86"),
    showlegend=False
))

# === Static Reference Point ===
fig.add_trace(go.Scatter(
    x=[2018], y=[emiss_2018],
    mode='markers+text',
    marker=dict(color='black', size=7),
    text=f'2018: {emiss_2018} MtCO2e',
    textposition='middle right',
    textfont=dict(size=15),
    showlegend=False
))

# === Legend Group: Scenarios ===
fig.add_trace(go.Scatter(
    x=[None], y=[None], mode='lines',
    line=dict(color='rgba(0,0,0,0)'),
    name='<br><br><br><b>Scenario</b>', showlegend=True, hoverinfo='skip'
))

fig.add_trace(go.Scatter(
    x=dfHist['index'],
    y=dfHist['순배출량'] / 1000,
    mode='lines', name='Historical Data',
    line=dict(color='black', width=1)
))

fig.add_trace(go.Scatter(
    x=dfOut[(dfOut['scenario'] == cp_scen_nm) & (dfOut['Year'] >= 2025)]['Year'],
    y=dfOut[(dfOut['scenario'] == cp_scen_nm) & (dfOut['Year'] >= 2025)]['value'],
    mode='lines', name='Current Policy',
    line=dict(color='#636EFA', width=1.5)
))

fig.add_trace(go.Scatter(
    x=dfOut[(dfOut['scenario'] == ep_scen_nm) & (dfOut['Year'] >= 2025)]['Year'],
    y=dfOut[(dfOut['scenario'] == ep_scen_nm) & (dfOut['Year'] >= 2025)]['value'],
    mode='lines', name='Enhanced Ambition',
    line=dict(color='#00CC96', width=1.5)
))

# fig.add_trace(go.Scatter(
#     x=dfOutPower[(dfOutPower['scenario'] == cp_scen_nm) & (dfOutPower['Year'] >= 2025)]['Year'],
#     y=dfOutPower[(dfOutPower['scenario'] == cp_scen_nm) & (dfOutPower['Year'] >= 2025)]['value'],
#     mode='lines', name='Current Policy',
#     line=dict(color='#636EFA', width=1.5, dash='dash'),
#     showlegend=False
# ))

# fig.add_trace(go.Scatter(
#     x=dfOutPower[(dfOutPower['scenario'] == ep_scen_nm) & (dfOutPower['Year'] >= 2005)]['Year'],
#     y=dfOutPower[(dfOutPower['scenario'] == ep_scen_nm) & (dfOutPower['Year'] >= 2005)]['value'],
#     mode='lines', name='Enhanced Ambition',
#     line=dict(color='#00CC96', width=1.5, dash='dash'),
#     showlegend=False
# ))

# === Axes & Layout ===
fig.update_layout(
    title="<b>Greenhouse gas emission pathways of South Korea</b>",
    title_font_size=28,
    title_x=0.43,
    legend_traceorder="normal",
    legend_title='',
    legend_font_size=15,
    plot_bgcolor='rgba(0,0,0,0)',
    width=1200,
    height=700,
    xaxis=dict(
        showgrid=False,
        title="Year", title_font_size=25,
        tickvals=list(range(1990, 2040, 5)),
        tickfont_size=15,
        range=[1987, 2045]
    ),
    yaxis=dict(
        showgrid=False,
        title="Emission (MtCO2e)", title_font_size=25,
        tickvals=list(range(0, 801, 100)),
        tickfont_size=15,
        range=[-30, 830]
    )
)

# === Reduction Boxes (overlay bars) ===
fig.add_trace(go.Scatter(
    x=[x_center - width / 2, x_center + width / 2, x_center + width / 2, x_center - width / 2],
    y=[emiss_2035_cur, emiss_2035_cur, emiss_2035_enh, emiss_2035_enh],
    fill='toself', fillcolor='rgba(0,204,150,0.3)',
    line=dict(color='rgba(0,0,0,0)'), hoverinfo='skip', showlegend=False
))
fig.add_trace(go.Scatter(
    x=[x_center - width / 2, x_center + width / 2, x_center + width / 2, x_center - width / 2],
    y=[emiss_2018, emiss_2018, emiss_2035_cur, emiss_2035_cur],
    fill='toself', fillcolor='rgba(99,110,250,0.3)',
    line=dict(color='rgba(0,0,0,0)'), hoverinfo='skip', showlegend=False
))

# === Reduction Labels ===
fig.add_annotation(
    x=x_center - 0.15, y=(emiss_2018 + emiss_2035_cur) / 2,
    text=f"<b>Current<br>Policy<br>-{reduc_cur:.1f}%</b>",
    showarrow=False, font=dict(size=14, color="#636EFA")
)
fig.add_annotation(
    x=x_center + 0.15, y=(emiss_2035_enh + emiss_2035_cur) / 2,
    text=f"<b>Enhanced<br>Ambition<br>-{reduc_enh:.1f}%</b>",
    showarrow=False, font=dict(size=14, color="#00CC96")
)

# === Reduction Boxes (overlay bars) ===
# fig.add_trace(go.Scatter(
#     x=[x_center - width / 2, x_center + width / 2, x_center + width / 2, x_center - width / 2],
#     y=[119.0679, 119.0679, 40.657, 40.657],
#     fill='toself', fillcolor='rgba(0,204,150,0.3)',
#     line=dict(color='rgba(0,0,0,0)'), hoverinfo='skip', showlegend=False
# ))

# fig.add_trace(go.Bar(
#     x=[x_center],
#     y=[278.84-40.657],
#     base=[40.657],  # for positioning
#     width=width,
#     marker=dict(
#         color='rgba(99,110,250,0.3)',
#         pattern=dict(
#             shape='\\',  # options: '/', '\\', 'x', '-', '|', '+', '.'
#             fillmode='overlay',
#             size=5,
#             solidity=0.2
#         )
#     ),
#     showlegend=False
# ))

# fig.add_trace(go.Scatter(
#     x=[x_center - width / 2, x_center + width / 2, x_center + width / 2, x_center - width / 2],
#     y=[278.84, 278.84, 119.0679, 119.0679],
#     fill='toself', fillcolor='rgba(99,110,250,0.3)',
#     line=dict(color='rgba(0,0,0,0)'), hoverinfo='skip', showlegend=False
# ))

# reduc_cur_power = 100 * (1 - 119.0679/278.84)
# reduc_enh_power = 100 * (1 - 40.657/278.84)

# # === Reduction Labels ===
# fig.add_annotation(
#     x=x_center - 0.15, y=(278.84 + 119.0679) / 2,
#     text=f"<b>-{reduc_cur_power:.1f}%</b>",
#     showarrow=False, font=dict(size=14, color="#636EFA")
# )
# fig.add_annotation(
#     x=x_center + 0.15, y=(40.657 + 119.0679) / 2,
#     text=f"<b>-{reduc_enh_power:.1f}%</b>",
#     showarrow=False, font=dict(size=14, color="#00CC96")
# )


# === Grid Lines (manual dashed lines) ===
for x in range(1990, 2040, 5):
    fig.add_shape(type="line", x0=x, x1=x, y0=-30, y1=830,
                  line=dict(color="LightGrey", width=1, dash="dash"),
                  layer='below')
for y in range(0, 831, 100):
    fig.add_shape(type="line", x0=1987, x1=2037, y0=y, y1=y,
                  line=dict(color="LightGrey", width=1, dash="dash"),
                  layer='below')
fig.add_shape(type="line", x0=1987, x1=2037, y0=0, y1=0,
              line=dict(color="LightGrey", width=1, dash="dash"),
              layer='above')

# === Optional: Highlight window 2025–2035 ===
fig.add_vrect(x0=2025, x1=2035, fillcolor="LightBlue", opacity=0.1,
              layer="below", line_width=0)

# === Box Around Plot ===
fig.add_shape(
    type="rect", xref="paper", yref="paper",
    x0=0, x1=1, y0=0, y1=1,
    line=dict(color="black", width=1),
    layer="above"
)

fig.add_annotation(
    text="w/o International Offset",
    xref="paper", 
    yref="paper",
    x=0.5,
    y=1.08,
    showarrow=False,
    font=dict(size=21, color="grey"),
    align="center"
)
fig.write_image("./fig/emiss_tot.png", scale=1)
fig

In [23]:
plotly_get_chrome

NameError: name 'plotly_get_chrome' is not defined